# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "92bf621a4b8baf5ded60f80957a2a613"
name = "audio-manager"
application_url = "https://clearly-gallery-argue-ns.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "blogs-comment.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://clearly-gallery-argue-ns.trycloudflare.com/auth/callback",
  "https://clearly-gallery-argue-ns.trycloudflare.com/auth/shopify/callback",
  "https://clearly-gallery-argue-ns.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
